### ISSUE TITLE
TODO 08/05-08/09

### ISSUE THREAD

**Issue by LorenTVu** [Trangvu801/dpool#1]
**Dashboard feature**

- [x] Linkify profile in comment
- [ ] #5
- [x] #4
- [x] Update guideline page.
- [x] Update the feedback page using Google Forms.

**LOGIN/SIGNUP**
- [ ] #2
- [ ] Forget password or username.
- [ ] Remember your account.

**Deployment**
- [ ] Deploy website.
- [ ] Save all the account passwords Vercel, Uploadthing, Stream, prisma, lucia.
